### ISSUE TITLE
How to use this plugin for time based anchor light switch?

### ISSUE THREAD

**Issue by KvotheBloodless** [sbender9/signalk-switch-automation#2]
Hi sbender9. Not an issue as such, but I would like to know if this plugin can be used to compare a value against a formatted datetime string, such as navigation.datetime. The format seems to be `yyyy-MM-ddThh:mm:ssZ`. Is there any way to configure for example:

IF navigation.speedOverGround < 0.5 AND navigation.datetime > ????-??-??T18:00:00+08 THEN electrical.switches.bank.107.anchor_light.state = 1

**Comment by Krillle** [comment]
If you don't intend to switch at fix times, but at sundown and sunrise, consider to use this plugin: 
https://www.npmjs.com/package/signalk-sunphases

With this you can check for after dawn with `notifications.nighttime = 'normal'`
